[package]
name = "astrid"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_8"] }
glib = "0.21.4"
gstreamer = { version = "0.24.3", features = ["v1_26"] }
gtk = { version = "0.10.2", package = "gtk4", features = ["gnome_49"] }
